## Compare BOM monthly station data with SILO monthy station data.

* BOM monthly rainfall data is for actual observations
* SILO monthly rainfall data interpolates missing observations with observations from nearby stations
* percentile analysis with SILO interpolated data seems to be giving too high of percentiles for July throughout central wheatbelt
* Will do comparison of the two datasets

In [1]:
import pandas as pd

In [18]:
# July rainfall observations from BOM. Contains 207 SILO database stations
df_bom_july = pd.read_csv(r'C:\Users\rj71b\geo-projects\wheatbelt_rainfall_analyser\data\interim\bom_201907.csv',
                         usecols = [0,3])

In [19]:
df_bom_july.head()

   station  rain
0     8002  42.3
1     8005  43.8
2     8008  55.0
3     8013  30.2
4     8014  33.8

In [20]:
# July rainfall observations from SILO database. Contains 335 staions
df_silo_july = pd.read_csv(r'C:\Users\rj71b\geo-projects\wheatbelt_rainfall_analyser\data\interim\new_silo_weather_july.csv',
                          usecols = [2,6])

In [21]:
df_silo_july.shape

(335, 2)

In [22]:
df_merge = pd.merge(df_silo_july, df_bom_july, on = "station", how = 'inner',
         suffixes=('_silo', '_bom'))

In [23]:
df_merge

     rain_silo  station  rain_bom
0         86.2     9519      86.2
1         85.4     9803      85.4
2         69.5     9509      69.5
3         28.5     9842      87.2
4         95.6     9771      95.6
5         85.4     9877      85.4
6         63.4     9628      75.1
7         60.6     9994      60.6
8         49.9     9738      49.9
9         51.6     9556      51.6
10        79.4     9617      79.4
11        77.3     9552      82.0
12        47.0     9587      47.0
13        45.8     9616      45.8
14       111.4     9573     111.4
15       102.3     9585     107.0
16       162.5     9590     168.8
17       122.6     9908     122.6
18       147.8     9592     149.2
19       153.6     9968     153.6
20       132.0     9611     131.9
21       130.1     9805     146.6
22       168.6     9904     168.6
23       107.8     9619      40.0
24       137.8     9215     137.8
25       108.6     9225     108.6
26        85.9     9007      86.9
27        79.8    10138      79.9
28       123.0     9193     123.0
29        69.6     9789      69.6
..         ...      ...       ...
233       27.0    10696      27.0
234       37.4    10513      37.4
235       30.4    10518      30.4
236       42.7    10546      43.0
237       30.2    10872      30.2
238       31.2    10560      31.2
239       40.6    10603      40.6
240       28.2    10565      28.2
241       33.1    10568      33.1
242       29.1    10705      29.1
243       29.2    10581      29.2
244       38.4    10665      32.2
245       36.7    10584      36.6
246       29.7    10606      29.0
247       29.7    10670      28.6
248       33.6    10911      33.6
249       43.4    10889      43.4
250       33.6    10692      33.6
251       28.1    10625      28.1
252       34.4    10638      34.4
253       65.3    10654      31.2
254       35.4    10662      35.4
255       49.0    10614      49.0
256       50.8    10505      31.6
257       49.0    10704      49.0
258       43.9    10542      46.4
259       34.8     9668      34.8
260       37.4    10641      37.0
261       47.8     9914      47.8
262       46.5    10647      46.5

[263 rows x 3 columns]

In [30]:
# 77 stations that have different rainfall observations
df_merge[(df_merge['rain_silo'] != df_merge['rain_bom'])]

     rain_silo  station  rain_bom  percent_diff
3         28.5     9842      87.2     67.316514
6         63.4     9628      75.1     15.579228
11        77.3     9552      82.0      5.731707
15       102.3     9585     107.0      4.392523
16       162.5     9590     168.8      3.732227
18       147.8     9592     149.2      0.938338
20       132.0     9611     131.9     -0.075815
21       130.1     9805     146.6     11.255116
23       107.8     9619      40.0   -169.500000
26        85.9     9007      86.9      1.150748
27        79.8    10138      79.9      0.125156
36        21.4     9542      21.2     -0.943396
38        32.0     9557      31.8     -0.628931
48        27.0     9739      36.2     25.414365
53        31.1     8013      30.2     -2.980132
57        57.4     8077      57.1     -0.525394
59        61.1     8079      61.0     -0.163934
60        62.9     8088       2.8  -2146.428571
62        36.7     8107      36.8      0.271739
71        57.5     8075      56.5     -1.769912
76        24.9     8294      19.0    -31.052632
84        81.7     9848      83.4      2.038369
87        47.8     9654      48.7      1.848049
90        45.9    10558      46.0      0.217391
95        37.3    10622      37.7      1.061008
97        32.1    10595      21.0    -52.857143
98        36.2     9835      35.7     -1.400560
101       67.2    10831      36.8    -82.608696
107       95.5    10525       3.0  -3083.333333
111       51.5    10866      51.4     -0.194553
..         ...      ...       ...           ...
132       34.6    10040      35.2      1.704545
135       10.1    10073      10.2      0.980392
137       74.1    10628       5.0  -1382.000000
144       35.4    10155      35.6      0.561798
149       55.2    10058      55.0     -0.363636
154       31.8    10077      30.9     -2.912621
157       48.0    10140      46.0     -4.347826
160       69.9     9014      70.0      0.142857
161       91.6     9018      92.5      0.972973
171       22.3    10019      21.8     -2.293578
172       31.1    10034      29.8     -4.362416
176       38.5    10702      20.0    -92.500000
183       53.3    10009      34.0    -56.764706
197       34.1    10158      20.0    -70.500000
206       24.4    10102      24.6      0.813008
208       36.5    10112      36.7      0.544959
209       36.0    12320      35.8     -0.558659
213       30.1    10136      20.4    -47.549020
222       47.8    10634      46.6     -2.575107
225       50.7    10527      49.4     -2.631579
228       53.2    10564      29.4    -80.952381
236       42.7    10546      43.0      0.697674
244       38.4    10665      32.2    -19.254658
245       36.7    10584      36.6     -0.273224
246       29.7    10606      29.0     -2.413793
247       29.7    10670      28.6     -3.846154
253       65.3    10654      31.2   -109.294872
256       50.8    10505      31.6    -60.759494
258       43.9    10542      46.4      5.387931
260       37.4    10641      37.0     -1.081081

[65 rows x 4 columns]

In [25]:
# add new column with percent difference between observations
df_merge['percent_diff'] = df_merge.apply(lambda row: (row.iloc[2]-row.iloc[0])/row.iloc[2]*100, axis=1)

In [34]:
# filter stations where diffence between rainfall observation is greater than 10 percent or less than -10 percent
#36 station where obsevation is greater than 10 percent
df_percent = df_merge[(df_merge['percent_diff'] > 10) | (df_merge['percent_diff'] < -10)]

In [39]:
df_percent

     rain_silo  station  rain_bom  percent_diff
3         28.5     9842      87.2     67.316514
6         63.4     9628      75.1     15.579228
21       130.1     9805     146.6     11.255116
23       107.8     9619      40.0   -169.500000
48        27.0     9739      36.2     25.414365
60        62.9     8088       2.8  -2146.428571
76        24.9     8294      19.0    -31.052632
97        32.1    10595      21.0    -52.857143
101       67.2    10831      36.8    -82.608696
107       95.5    10525       3.0  -3083.333333
115       52.3    10643      41.8    -25.119617
137       74.1    10628       5.0  -1382.000000
176       38.5    10702      20.0    -92.500000
183       53.3    10009      34.0    -56.764706
197       34.1    10158      20.0    -70.500000
213       30.1    10136      20.4    -47.549020
228       53.2    10564      29.4    -80.952381
244       38.4    10665      32.2    -19.254658
253       65.3    10654      31.2   -109.294872
256       50.8    10505      31.6    -60.759494

In [28]:
'https://legacy.longpaddock.qld.gov.au/cgi-bin/silo/PatchedPointDataset.php?format=Monthly&station=10505&start=20190630&finish=20190731&username=SILO1838&password=K16AM7NG'

'https://legacy.longpaddock.qld.gov.au/cgi-bin/silo/PatchedPointDataset.php?format=Monthly&station=10505&start=20190630&finish=20190731&username=SILO1838&password=K16AM7NG'